services:
  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
    networks:
      - "app-network"

  app:
    container_name: tv_app
    build: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "12345"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/postgres"
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: "4"
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_LOCATIONS: "classpath:migration"
      SPRING_FLYWAY_SCHEMAS: "televisions"
    ports:
      - "8080:8080"
    networks:
      - "app-network"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge
